### ISSUE TITLE
Cannot pull/start container

### ISSUE THREAD

**Issue by vlkdev** [hakoerber/talks#1]
Get this error after executing command:

`docker run -p 8000:8000 -v $PWD:/doc -ti --rm registry.haktec.de/builddoc presentation-html-serve
`

Unable to find image 'registry.haktec.de/builddoc:latest' locally
docker: Error response from daemon: manifest for registry.haktec.de/builddoc:latest not found.
See 'docker run --help'.

**Comment by hakoerber** [comment]
Registry was broken, should be fixed now
